apiVersion: apps/v1
kind: Deployment
metadata:
  name: career-app
  labels:
    app: career-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: career-app
  template:
    metadata:
      labels:
        app: career-app
    spec:
      containers:
      - name: career-app
        image: dhruvalsharma59/career-app:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: career-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: career-app
